modules_dir = "artifacts/"

[[module]]
    name = "sqlite3"

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "./tmp" }

[[module]]
    name = "dht"
    mem_pages_count = 100
    logger_enabled = true