modules_dir = "artifacts/"

[[module]]
    name = "sqlite3"

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "./tmp" }

[[module]]
    name = "dht"
    max_heap_size = "100 KiB"
    logger_enabled = true